label.productCode=Product Code
label.productName=Product Name
label.lotCode=Lot code
label.expiryDate=Expiry date
label.vvmStatus=VVM Status
label.itemizedReasons=Itemized reasons
label.currentStock.doses=Current Stock\n(Doses)
label.currentStock.packs=Current Stock\n(Packs)
label.soh.doses=Stock On Hand\n(Doses)
label.soh.packs=Stock On Hand\n(Packs)
label.noLotDefined=No lot defined
label.quantity.prefix=+