title.physicalInventory=Submitted Physical Inventory
label.inventoryDate=Physical inventory for date
label.facility=Facility
label.program=Program
label.submittedOn=Submitted into system on
label.by=by
label.productCode=Product Code
label.productName=Product Name
label.lotCode=Lot code
label.expiryDate=Expiry date
label.vvmStatus=VVM Status
label.itemizedReasons=Itemized Reasons
label.currentStockDoses=Current Stock (Doses)
label.currentStockPacks=Current Stock (Packs)
label.sohDoses=Stock On Hand (Doses)
label.sohPacks=Stock On Hand (Packs)
label.noLotDefined=No lot defined
label.page=Page
label.of=of