title.stockCardReport=Stock Card Report
label.facility=Facility
label.facilityCode=Facility code
label.program=Program
label.programCode=Program Code
label.product=Product
label.productCode=Product Code
label.soh=SOH
label.lotNumber=Lot number
label.expiryDate=Expiry date
label.cardLineItems=Card Line Items
label.page=Page
label.of=of
label.column.date=Date
label.column.receiveFrom=Receive from
label.column.issueTo=Issue to
label.column.reason=Reason
label.column.adjustment=Adjustment
label.column.soh=Stock on hand
label.column.performedBy=Performed by
label.column.signature=Signature