title.stockCardSummaryReport=Stock Card Summary Report
label.facility=Facility
label.facilityCode=Facility code
label.program=Program
label.programCode=Program Code
label.column.productCode=Product Code
label.column.product=Product
label.column.program=Program
label.column.facility=Facility
label.column.lotCode=Lot Code
label.column.expiryDate=Expiry Date
label.column.lastUpdate=Last update
label.column.soh=SOH
label.noLotDefined=No lot defined
label.page=Page
label.of=of